### ISSUE TITLE
*Important* Local Pickup column in cart displaying incorrect information

### ISSUE THREAD

**Issue by BigActual** [realbig/napoleonbeesupply-theme-2017#14]
Package Bees show No in the Local Pickup column of the shopping cart when they should say yes.
https://d.pr/free/i/YUSUqG
https://d.pr/free/i/DGDU9Q
I verified that the products are configured correctly in Edit Product>Product Data>Shipping>Shipping Class>[Local Pickup]

The customer has a very short window to capture orders. Please elevate the importance of addressing this issue.

**Comment by d4mation** [comment]
This was caused by the Theme expecting the Products to be Virtual if they are in-store pick-up only. It now handles the shipping correctly (Doesn't ask to calculate it) and it shows "Yes" in that column, as well as a notice above the cart.

https://github.com/realbig/napoleonbeesupply-theme-2017/blob/8d8a6ed0e67a084429be83012db27e7706ec3591/woocommerce/cart/cart.php#L83-L89

https://github.com/realbig/napoleonbeesupply-theme-2017/blob/8d8a6ed0e67a084429be83012db27e7706ec3591/library/woocommerce.php#L158-L160
